### ISSUE TITLE
add to MELPA and automatically download toml dep

### ISSUE THREAD

**Issue by avocadoras** [galaunay/poetry.el#1]
Hi, 

It would be nice for an easy install via MELPA.

Step #2 says to just `(add-to-list 'load-path "/path/to/poetry.el/directory")` and the `(require 'poetry)`. However I got this message when I tried to evaluate the second form

```
Debugger entered--Lisp error: (file-error "Cannot open load file" "Not a directory" "toml")
  require(toml)
  eval-buffer(#<buffer  *load*> nil "/Users/jr/.emacs.d/el/poetry.el" nil t)  ; Reading at buffer position 933
  load-with-code-conversion("/Users/jr/.emacs.d/el/poetry.el" "/Users/jr/.emacs.d/el/poetry.el" nil t)
  require(poetry)
  eval((require 'poetry) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

I solved by installing `(use-package toml :ensure t)`. Could this be handled by `poetry.el` as well if/when published in MELPA?

**Comment by galaunay** [comment]
Hi, 

Thanks for the feedback.
I intend to add poetry.el to Melpa as soon as possible.
But I think it still need a bit of work to deserve it.

When properly published, it will install `toml` and the other dependencies automatically.

I'll add a note in the readme to indicate that to potential other users.

**Comment by galaunay** [comment]
Poetry is now available on Melpa !
