### ISSUE TITLE
[BUG] Issues running venv toggle after the new poetry 1.0 release

### ISSUE THREAD

**Issue by finnkauski** [galaunay/poetry.el#12]
# Issue
Hey, currently with the new release of poetry (1.0) I can't seem to toggle the virtual environment on. 
The option is simply not there and M-x ing it has been giving me issue. 

Sorry for the non specificity of the report, however I have since moved on to the `pipenv` as an intermediary solution so I can not remember what issues I had previously. However thought that its wise to report. I have seen some forks that attempt to fix this. Maybe you can accept or ask for a PR? 

Or maybe i am just being dense.

# System Specs
Please ask if needed.

**Comment by thomasf** [comment]
It looks like https://github.com/galaunay/poetry.el/pull/11  solves this issue

**Comment by galaunay** [comment]
As @thomasf said, it should be fixed by #11 as soon as I fix the tests and merge it.

**Comment by finnkauski** [comment]
Awesome! Thanks for the hard work folks. Love the package.
