### ISSUE TITLE
`poetry-venv-workon` returns error

### ISSUE THREAD

**Issue by joostkremers** [galaunay/poetry.el#17]
When I try to do `M-: (poetry-venv-workon)`, I get the following error:

```
Debugger entered--Lisp error: (wrong-type-argument characterp "config")
  mapconcat(identity (("config") ("virtualenvs.in-project")) " ")
  poetry-do-call(config ("virtualenvs.in-project") nil nil t)
  poetry-call(config ("virtualenvs.in-project") nil nil t)
  poetry-get-configuration("virtualenvs.in-project")
  poetry-get-virtualenv()
  poetry-venv-workon()
  eval((poetry-venv-workon) t)
  eval-expression((poetry-venv-workon) nil nil 127)
  funcall-interactively(eval-expression (poetry-venv-workon) nil nil 127)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

This is on Emacs 27.0.90. On another machine, which runs Emacs 26, activating the venv works just fine.

BTW, I was trying to activate the venv this way (with `eval-expression`) because the menu that pops up when I do `M-x poetry` doesn't have the option to activate the venv. Guess that might be related to the error I get.

**Comment by galaunay** [comment]
it seems that its failing on this line 
```
(cl-concatenate 'list (list (symbol-name command)) args)
```

I don't have emacs 27 on hand, but I suspect `cl-concatenate` to have changed a bit.
Could you provide the documentation for `cl-concatenate` ?

**Comment by joostkremers** [comment]
The doc string hasn't changed, but the function's return value has. I would be highly surprised if that isn't a bug, so I reported it here:

https://lists.gnu.org/archive/html/bug-gnu-emacs/2020-03/msg00897.html

**Comment by joostkremers** [comment]
Yup, it's an Emacs bug and it will be fixed in the official v27 release. So I'm closing this now.
