### ISSUE TITLE
cannot create new projects with `M-x poetry` 

### ISSUE THREAD

**Issue by avocadoras** [galaunay/poetry.el#2]
I'm on macOS Mojave Emacs 26.1.... I cannot create new projects.

Steps to reproduce:

1. `M-x poetry`
2. `n`
3. enter in minibuffer `poetry-testing`
4. Error with message "let*: Wrong type argument: stringp, 47"

**Comment by galaunay** [comment]
Should be fixed by now.

Silly mistakes during refactoring, 
that is why we need some tests...
