### ISSUE TITLE
Poetry.el doesn't seems to take in charge python-shell compile mode

### ISSUE THREAD

**Issue by mikefaille** [galaunay/poetry.el#20]
I think if we can have support for python-shell to "compile" that would be great.

Unless there is an easy workaround ?

**Comment by galaunay** [comment]
I am not sure if I understand what you mean.
You would like to have the prompt offering you the right python binaries when running `M-x compile` ?

Something like `Compile command: /usr/bin/poetry run python YOURFILE.py` ?

Note to myself: 
if so, it is quite easy to do with something like that:
``` elisp
(add-hook 'python-mode-hook
          (lambda ()
            (when (poetry-find-project-root)
              (set (make-local-variable 'compile-command)
                   (concat (executable-find "poetry")
                           " run python "
                           (if buffer-file-name
                               (shell-quote-argument
                                (file-name-nondirectory buffer-file-name))))))))
```
The script will run in the poetry virtualenv

**Comment by mikefaille** [comment]
It works for me then
