### ISSUE TITLE
create new project dwim

### ISSUE THREAD

**Issue by avocadoras** [galaunay/poetry.el#3]
Currently, `M-x poetry` only installs projects on existing directories.

Would be nice that if the given project name in prompt does not exist then create new directory with that name.

# Steps to reproduce
1. Go to `$HOME`
2. `C-c d`
3. `M-x poetry`
4. insert in minibuffer `poet-testing`
## Error
error: `apply: Setting current directory: No such file or directory, /Users/jr/poet-testing`

# OS and Emacs version
macOS mojae , Emacs 26.1

**Comment by galaunay** [comment]
Thanks for the feedback.
It is now creating directories when necessary.

**Comment by avocadoras** [comment]
@galaunay i updated the package and still seeing this issue :/
