### ISSUE TITLE
ANSI color issue of `poetry show`

### ISSUE THREAD

**Issue by Yevgnen** [galaunay/poetry.el#9]
ANSI output seems not properly handled in `poetry show`.

<img width="728" alt="Screen Shot 2019-06-30 at 2 29 42 PM" src="https://user-images.githubusercontent.com/16749790/60393172-a089a480-9b43-11e9-9aaa-8d2938e2e257.png">

**Comment by galaunay** [comment]
Thanks for reporting.

I think it may be due to the recent changes in `compilation-mode`.
Which version of Emacs are you using ?

**Comment by Yevgnen** [comment]
It's `GNU Emacs 26.2.90 (build 1, x86_64-apple-darwin18.6.0, Carbon Version 158 AppKit 1671.5) of 2019-06-19`

**Comment by galaunay** [comment]
So it is not the problem...

Can I ask what is the result of `(poetry-show-get-packages)` and what shows the `*poetry*` buffer after running this command ?

**Comment by Yevgnen** [comment]
The result of `(poetry-show-get-packages` is 

    (#("[31mzipp                  [0m [36m0.5.1                                                                                                    [0m" 0 146 (fontified nil)) #("[31myapf                  [0m [36m0.27.0                                                                                                   [0m" 0 146 (fontified nil)) #("[31mwrapt                 [0m [36m1.11.2                                                                                                   [0m" 0 146 (fontified nil)) #("[31mwidgetsnbextension    [0m [36m3.5.0                                                                                                    [0m" 0 57 (fontified nil) 57 146 (fontified nil)) #("[31mwheel                 [0m [36m0.33.4                                                                                                   [0m" 0 146 (fontified nil)) #("[31mwebencodings          [0m [36m0.5.1                                                                                                    [0m" 0 146 (fontified nil)) #("[31mwcwidth               [0m [36m0.1.7                                                                                                    [0m" 0 146 (fontified nil)) #("[31murllib3               [0m [36m1.25.3                                                                                                   [0m" 0 146 (fontified nil)) #("[31mtyping                [0m [36m3.7.4                                                                                                    [0m" 0 146 (fontified nil)) #("[31mtyped-ast             [0m [36m1.4.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mtraitlets             [0m [36m4.3.2                                                                                                    [0m" 0 62 (fontified nil) 62 146 (fontified nil)) #("[31mtqdm                  [0m [36m4.32.2                                                                                                   [0m" 0 146 (fontified nil)) #("[31mtornado               [0m [36m6.0.3                                                                                                    [0m" 0 146 (fontified nil)) #("[31mtorchvision           [0m [36m0.3.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mtorchtext             [0m [36m0.3.1                                                                                                    [0m" 0 146 (fontified nil)) #("[31mtorch                 [0m [36m1.1.0.post2                                                                                              [0m" 0 146 (fontified nil)) #("[31mtext-unidecode        [0m [36m1.2                                                                                                      [0m" 0 146 (fontified nil)) #("[31mtestpath              [0m [36m0.4.2                                                                                                    [0m" 0 67 (fontified nil) 67 146 (fontified nil)) #("[31mterminado             [0m [36m0.8.2                                                                                                    [0m" 0 146 (fontified nil)) #("[31mtabulate              [0m [36m0.8.3                                                                                                    [0m" 0 146 (fontified nil)) #("[31msympy                 [0m [36m1.4                                                                                                      [0m" 0 146 (fontified nil)) #("[31mstatsmodels           [0m [36m0.10.0                                                                                                   [0m" 0 146 (fontified nil)) #("[31msoupsieve             [0m [36m1.9.2                                                                                                    [0m" 0 146 (fontified nil)) #("[31msklearn-pandas        [0m [36m1.8.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31msklearn               [0m [36m0.0                                                                                                      [0m" 0 72 (fontified nil) 72 146 (fontified nil)) #("[31msix                   [0m [36m1.12.0                                                                                                   [0m" 0 146 (fontified nil)) #("[31msend2trash            [0m [36m1.5.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mseaborn               [0m [36m0.9.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mscipy                 [0m [36m1.3.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mscikit-learn          [0m [36m0.21.2                                                                                                   [0m" 0 146 (fontified nil)) #("[31mretrying              [0m [36m1.3.3                                                                                                    [0m" 0 146 (fontified nil)) #("[31mrequests              [0m [36m2.22.0                                                                                                   [0m" 0 77 (fontified nil) 77 146 (fontified nil)) #("[31mredis                 [0m [36m3.2.1                                                                                                    [0m" 0 146 (fontified nil)) #("[31mray                   [0m [36m0.7.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mqtconsole             [0m [36m4.5.1                                                                                                    [0m" 0 146 (fontified nil)) #("[31mpyzmq                 [0m [36m18.0.2                                                                                                   [0m" 0 146 (fontified nil)) #("[31mpyyaml                [0m [36m5.1.1                                                                                                    [0m" 0 146 (fontified nil)) #("[31mpyutils               [0m [36m0.0.1 ../pyutils                                                                                         [0m" 0 146 (fontified nil)) #("[31mpytz                  [0m [36m2019.1                                                                                                   [0m" 0 82 (fontified nil) 82 146 (fontified nil)) #("[31mpython-language-server[0m [36m0.27.0                                                                                                   [0m" 0 146 (fontified nil)) #("[31mpython-jsonrpc-server [0m [36m0.2.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mpython-dateutil       [0m [36m2.8.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mpytest-pylint         [0m [36m0.14.0                                                                                                   [0m" 0 146 (fontified nil)) #("[31mpytest                [0m [36m5.0.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mpytesseract           [0m [36m0.2.7                                                                                                    [0m" 0 146 (fontified nil)) #("[31mpyrsistent            [0m [36m0.15.2                                                                                                   [0m" 0 87 (fontified nil) 87 146 (fontified nil)) #("[31mpyparsing             [0m [36m2.4.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mpylint                [0m [36m2.3.1                                                                                                    [0m" 0 146 (fontified nil)) #("[31mpygments              [0m [36m2.4.2                                                                                                    [0m" 0 146 (fontified nil)) #("[31mpyflakes              [0m [36m2.1.1                                                                                                    [0m" 0 146 (fontified nil)) #("[31mpycodestyle           [0m [36m2.5.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mpy                    [0m [36m1.8.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mptyprocess            [0m [36m0.6.0                                                                                                    [0m" 0 92 (fontified nil) 92 146 (fontified nil)) #("[31mprompt-toolkit        [0m [36m2.0.9                                                                                                    [0m" 0 146 (fontified nil)) #("[31mprometheus-client     [0m [36m0.7.1                                                                                                    [0m" 0 146 (fontified nil)) #("[31mpluggy                [0m [36m0.12.0                                                                                                   [0m" 0 146 (fontified nil)) #("[31mplotly                [0m [36m3.10.0                                                                                                   [0m" 0 146 (fontified nil)) #("[31mpillow                [0m [36m6.1.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mpickleshare           [0m [36m0.7.5                                                                                                    [0m" 0 146 (fontified nil)) #("[31mphik                  [0m [36m0.9.8                                                                                                    [0m" 0 97 (fontified nil) 97 146 (fontified nil)) #("[31mpexpect               [0m [36m4.7.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mpatsy                 [0m [36m0.5.1                                                                                                    [0m" 0 146 (fontified nil)) #("[31mparso                 [0m [36m0.5.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mpandocfilters         [0m [36m1.4.2                                                                                                    [0m" 0 146 (fontified nil)) #("[31mpandas-profiling      [0m [36m2.0.3                                                                                                    [0m" 0 146 (fontified nil)) #("[31mpandas                [0m [36m0.24.2                                                                                                   [0m" 0 146 (fontified nil)) #("[31mpackaging             [0m [36m19.0                                                                                                     [0m" 0 102 (fontified nil) 102 146 (fontified nil)) #("[31mnumpy                 [0m [36m1.16.4                                                                                                   [0m" 0 146 (fontified nil)) #("[31mnumba                 [0m [36m0.44.1                                                                                                   [0m" 0 146 (fontified nil)) #("[31mnotebook              [0m [36m5.7.8                                                                                                    [0m" 0 146 (fontified nil)) #("[31mnbformat              [0m [36m4.4.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mnbconvert             [0m [36m5.5.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mmpmath                [0m [36m1.1.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mmore-itertools        [0m [36m7.1.0                                                                                                    [0m" 0 107 (fontified nil) 107 146 (fontified nil)) #("[31mmodin                 [0m [36m0.5.3                                                                                                    [0m" 0 146 (fontified nil)) #("[31mmistune               [0m [36m0.8.4                                                                                                    [0m" 0 146 (fontified nil)) #("[31mmissingno             [0m [36m0.4.1                                                                                                    [0m" 0 146 (fontified nil)) #("[31mmccabe                [0m [36m0.6.1                                                                                                    [0m" 0 146 (fontified nil)) #("[31mmatplotlib            [0m [36m3.1.1                                                                                                    [0m" 0 146 (fontified nil)) #("[31mmarkupsafe            [0m [36m1.1.1                                                                                                    [0m" 0 146 (fontified nil)) #("[31mlxml                  [0m [36m4.3.4                                                                                                    [0m" 0 112 (fontified nil) 112 146 (fontified nil)) #("[31mllvmlite              [0m [36m0.29.0                                                                                                   [0m" 0 146 (fontified nil)) #("[31mline-profiler         [0m [36m2.1.1 /Users/user/Downloads/line_profiler/dist/line_profiler-2.1.1-cp37-cp37m-macosx_10_14_x86_64.whl[0m" 0 146 (fontified nil)) #("[31mlazy-object-proxy     [0m [36m1.4.1                                                                                                    [0m" 0 146 (fontified nil)) #("[31mkiwisolver            [0m [36m1.1.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mjupyter-core          [0m [36m4.5.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mjupyter-console       [0m [36m6.0.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mjupyter-client        [0m [36m5.2.4                                                                                                    [0m" 0 117 (fontified nil) 117 146 (fontified nil)) #("[31mjupyter               [0m [36m1.0.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mjsonschema            [0m [36m3.0.1                                                                                                    [0m" 0 146 (fontified nil)) #("[31mjoblib                [0m [36m0.13.2                                                                                                   [0m" 0 146 (fontified nil)) #("[31mjinja2                [0m [36m2.10.1                                                                                                   [0m" 0 146 (fontified nil)) #("[31mjedi                  [0m [36m0.13.3                                                                                                   [0m" 0 146 (fontified nil)) #("[31misort                 [0m [36m4.3.21                                                                                                   [0m" 0 146 (fontified nil)) #("[31mipywidgets            [0m [36m7.5.0                                                                                                    [0m" 0 122 (fontified nil) 122 146 (fontified nil)) #("[31mipython-genutils      [0m [36m0.2.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mipython               [0m [36m7.6.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mipykernel             [0m [36m5.1.1                                                                                                    [0m" 0 146 (fontified nil)) #("[31mimportlib-metadata    [0m [36m0.18                                                                                                     [0m" 0 146 (fontified nil)) #("[31midna                  [0m [36m2.8                                                                                                      [0m" 0 146 (fontified nil)) #("[31mhtmlmin               [0m [36m0.1.12                                                                                                   [0m" 0 146 (fontified nil)) #("[31mhtml5lib              [0m [36m1.0.1                                                                                                    [0m" 0 127 (fontified nil) 127 146 (fontified nil)) #("[31mh2o                   [0m [36m3.24.0.5                                                                                                 [0m" 0 146 (fontified nil)) #("[31mfuture                [0m [36m0.17.1                                                                                                   [0m" 0 146 (fontified nil)) #("[31mfuncsigs              [0m [36m1.0.2                                                                                                    [0m" 0 146 (fontified nil)) #("[31mflatbuffers           [0m [36m1.11                                                                                                     [0m" 0 146 (fontified nil)) #("[31mflake8                [0m [36m3.7.7                                                                                                    [0m" 0 146 (fontified nil)) #("[31mfilelock              [0m [36m3.0.12                                                                                                   [0m" 0 146 (fontified nil)) #("[31mfaker                 [0m [36m1.0.7                                                                                                    [0m" 0 132 (fontified nil) 132 146 (fontified nil)) #("[31mentrypoints           [0m [36m0.3                                                                                                      [0m" 0 146 (fontified nil)) #("[31mdefusedxml            [0m [36m0.6.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mdecorator             [0m [36m4.4.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mcython                [0m [36m0.29.11                                                                                                  [0m" 0 146 (fontified nil)) #("[31mcycler                [0m [36m0.10.0                                                                                                   [0m" 0 146 (fontified nil)) #("[31mconfuse               [0m [36m1.0.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mcolorama              [0m [36m0.4.1                                                                                                    [0m" 0 137 (fontified nil) 137 146 (fontified nil)) #("[31mclick                 [0m [36m7.0                                                                                                      [0m" 0 146 (fontified nil)) #("[31mchardet               [0m [36m3.0.4                                                                                                    [0m" 0 146 (fontified nil)) #("[31mcertifi               [0m [36m2019.6.16                                                                                                [0m" 0 146 (fontified nil)) #("[31mcategory-encoders     [0m [36m2.0.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mbs4                   [0m [36m0.0.1                                                                                                    [0m" 0 146 (fontified nil)) #("[31mbleach                [0m [36m3.1.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mbeautifulsoup4        [0m [36m4.7.1                                                                                                    [0m" 0 142 (fontified nil) 142 146 (fontified nil)) #("[31mbackcall              [0m [36m0.1.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mautoflake             [0m [36m1.3                                                                                                      [0m" 0 146 (fontified nil)) #("[31mattrs                 [0m [36m19.1.0                                                                                                   [0m" 0 146 (fontified nil)) #("[31matomicwrites          [0m [36m1.3.0                                                                                                    [0m" 0 146 (fontified nil)) #("[31mastroid               [0m [36m2.2.5                                                                                                    [0m" 0 146 (fontified nil)) #("[31mappnope               [0m [36m0.1.0                                                                                                    [0m" 0 146 (fontified nil)) #("Creating virtualenv [32mgeneral-py3.7[0m in /Users/user/.pyenv/versions" 0 77 (fontified nil)))


The content of `*poetry*` buffer is 

    Creating virtualenv [32mgeneral-py3.7[0m in /Users/user/.pyenv/versions
    [31mappnope               [0m [36m0.1.0                                                                                                    [0m
    [31mastroid               [0m [36m2.2.5                                                                                                    [0m
    [31matomicwrites          [0m [36m1.3.0                                                                                                    [0m
    [31mattrs                 [0m [36m19.1.0                                                                                                   [0m
    [31mautoflake             [0m [36m1.3                                                                                                      [0m
    [31mbackcall              [0m [36m0.1.0                                                                                                    [0m
    [31mbeautifulsoup4        [0m [36m4.7.1                                                                                                    [0m
    [31mbleach                [0m [36m3.1.0                                                                                                    [0m
    [31mbs4                   [0m [36m0.0.1                                                                                                    [0m
    [31mcategory-encoders     [0m [36m2.0.0                                                                                                    [0m
    [31mcertifi               [0m [36m2019.6.16                                                                                                [0m
    [31mchardet               [0m [36m3.0.4                                                                                                    [0m
    [31mclick                 [0m [36m7.0                                                                                                      [0m
    [31mcolorama              [0m [36m0.4.1                                                                                                    [0m
    [31mconfuse               [0m [36m1.0.0                                                                                                    [0m
    [31mcycler                [0m [36m0.10.0                                                                                                   [0m
    [31mcython                [0m [36m0.29.11                                                                                                  [0m
    [31mdecorator             [0m [36m4.4.0                                                                                                    [0m
    [31mdefusedxml            [0m [36m0.6.0                                                                                                    [0m
    [31mentrypoints           [0m [36m0.3                                                                                                      [0m
    [31mfaker                 [0m [36m1.0.7                                                                                                    [0m
    [31mfilelock              [0m [36m3.0.12                                                                                                   [0m
    [31mflake8                [0m [36m3.7.7                                                                                                    [0m
    [31mflatbuffers           [0m [36m1.11                                                                                                     [0m
    [31mfuncsigs              [0m [36m1.0.2                                                                                                    [0m
    [31mfuture                [0m [36m0.17.1                                                                                                   [0m
    [31mh2o                   [0m [36m3.24.0.5                                                                                                 [0m
    [31mhtml5lib              [0m [36m1.0.1                                                                                                    [0m
    [31mhtmlmin               [0m [36m0.1.12                                                                                                   [0m
    [31midna                  [0m [36m2.8                                                                                                      [0m
    [31mimportlib-metadata    [0m [36m0.18                                                                                                     [0m
    [31mipykernel             [0m [36m5.1.1                                                                                                    [0m
    [31mipython               [0m [36m7.6.0                                                                                                    [0m
    [31mipython-genutils      [0m [36m0.2.0                                                                                                    [0m
    [31mipywidgets            [0m [36m7.5.0                                                                                                    [0m
    [31misort                 [0m [36m4.3.21                                                                                                   [0m
    [31mjedi                  [0m [36m0.13.3                                                                                                   [0m
    [31mjinja2                [0m [36m2.10.1                                                                                                   [0m
    [31mjoblib                [0m [36m0.13.2                                                                                                   [0m
    [31mjsonschema            [0m [36m3.0.1                                                                                                    [0m
    [31mjupyter               [0m [36m1.0.0                                                                                                    [0m
    [31mjupyter-client        [0m [36m5.2.4                                                                                                    [0m
    [31mjupyter-console       [0m [36m6.0.0                                                                                                    [0m
    [31mjupyter-core          [0m [36m4.5.0                                                                                                    [0m
    [31mkiwisolver            [0m [36m1.1.0                                                                                                    [0m
    [31mlazy-object-proxy     [0m [36m1.4.1                                                                                                    [0m
    [31mline-profiler         [0m [36m2.1.1 /Users/user/Downloads/line_profiler/dist/line_profiler-2.1.1-cp37-cp37m-macosx_10_14_x86_64.whl[0m
    [31mllvmlite              [0m [36m0.29.0                                                                                                   [0m
    [31mlxml                  [0m [36m4.3.4                                                                                                    [0m
    [31mmarkupsafe            [0m [36m1.1.1                                                                                                    [0m
    [31mmatplotlib            [0m [36m3.1.1                                                                                                    [0m
    [31mmccabe                [0m [36m0.6.1                                                                                                    [0m
    [31mmissingno             [0m [36m0.4.1                                                                                                    [0m
    [31mmistune               [0m [36m0.8.4                                                                                                    [0m
    [31mmodin                 [0m [36m0.5.3                                                                                                    [0m
    [31mmore-itertools        [0m [36m7.1.0                                                                                                    [0m
    [31mmpmath                [0m [36m1.1.0                                                                                                    [0m
    [31mnbconvert             [0m [36m5.5.0                                                                                                    [0m
    [31mnbformat              [0m [36m4.4.0                                                                                                    [0m
    [31mnotebook              [0m [36m5.7.8                                                                                                    [0m
    [31mnumba                 [0m [36m0.44.1                                                                                                   [0m
    [31mnumpy                 [0m [36m1.16.4                                                                                                   [0m
    [31mpackaging             [0m [36m19.0                                                                                                     [0m
    [31mpandas                [0m [36m0.24.2                                                                                                   [0m
    [31mpandas-profiling      [0m [36m2.0.3                                                                                                    [0m
    [31mpandocfilters         [0m [36m1.4.2                                                                                                    [0m
    [31mparso                 [0m [36m0.5.0                                                                                                    [0m
    [31mpatsy                 [0m [36m0.5.1                                                                                                    [0m
    [31mpexpect               [0m [36m4.7.0                                                                                                    [0m
    [31mphik                  [0m [36m0.9.8                                                                                                    [0m
    [31mpickleshare           [0m [36m0.7.5                                                                                                    [0m
    [31mpillow                [0m [36m6.1.0                                                                                                    [0m
    [31mplotly                [0m [36m3.10.0                                                                                                   [0m
    [31mpluggy                [0m [36m0.12.0                                                                                                   [0m
    [31mprometheus-client     [0m [36m0.7.1                                                                                                    [0m
    [31mprompt-toolkit        [0m [36m2.0.9                                                                                                    [0m
    [31mptyprocess            [0m [36m0.6.0                                                                                                    [0m
    [31mpy                    [0m [36m1.8.0                                                                                                    [0m
    [31mpycodestyle           [0m [36m2.5.0                                                                                                    [0m
    [31mpyflakes              [0m [36m2.1.1                                                                                                    [0m
    [31mpygments              [0m [36m2.4.2                                                                                                    [0m
    [31mpylint                [0m [36m2.3.1                                                                                                    [0m
    [31mpyparsing             [0m [36m2.4.0                                                                                                    [0m
    [31mpyrsistent            [0m [36m0.15.2                                                                                                   [0m
    [31mpytesseract           [0m [36m0.2.7                                                                                                    [0m
    [31mpytest                [0m [36m5.0.0                                                                                                    [0m
    [31mpytest-pylint         [0m [36m0.14.0                                                                                                   [0m
    [31mpython-dateutil       [0m [36m2.8.0                                                                                                    [0m
    [31mpython-jsonrpc-server [0m [36m0.2.0                                                                                                    [0m
    [31mpython-language-server[0m [36m0.27.0                                                                                                   [0m
    [31mpytz                  [0m [36m2019.1                                                                                                   [0m
    [31mpyutils               [0m [36m0.0.1 ../pyutils                                                                                         [0m
    [31mpyyaml                [0m [36m5.1.1                                                                                                    [0m
    [31mpyzmq                 [0m [36m18.0.2                                                                                                   [0m
    [31mqtconsole             [0m [36m4.5.1                                                                                                    [0m
    [31mray                   [0m [36m0.7.0                                                                                                    [0m
    [31mredis                 [0m [36m3.2.1                                                                                                    [0m
    [31mrequests              [0m [36m2.22.0                                                                                                   [0m
    [31mretrying              [0m [36m1.3.3                                                                                                    [0m
    [31mscikit-learn          [0m [36m0.21.2                                                                                                   [0m
    [31mscipy                 [0m [36m1.3.0                                                                                                    [0m
    [31mseaborn               [0m [36m0.9.0                                                                                                    [0m
    [31msend2trash            [0m [36m1.5.0                                                                                                    [0m
    [31msix                   [0m [36m1.12.0                                                                                                   [0m
    [31msklearn               [0m [36m0.0                                                                                                      [0m
    [31msklearn-pandas        [0m [36m1.8.0                                                                                                    [0m
    [31msoupsieve             [0m [36m1.9.2                                                                                                    [0m
    [31mstatsmodels           [0m [36m0.10.0                                                                                                   [0m
    [31msympy                 [0m [36m1.4                                                                                                      [0m
    [31mtabulate              [0m [36m0.8.3                                                                                                    [0m
    [31mterminado             [0m [36m0.8.2                                                                                                    [0m
    [31mtestpath              [0m [36m0.4.2                                                                                                    [0m
    [31mtext-unidecode        [0m [36m1.2                                                                                                      [0m
    [31mtorch                 [0m [36m1.1.0.post2                                                                                              [0m
    [31mtorchtext             [0m [36m0.3.1                                                                                                    [0m
    [31mtorchvision           [0m [36m0.3.0                                                                                                    [0m
    [31mtornado               [0m [36m6.0.3                                                                                                    [0m
    [31mtqdm                  [0m [36m4.32.2                                                                                                   [0m
    [31mtraitlets             [0m [36m4.3.2                                                                                                    [0m
    [31mtyped-ast             [0m [36m1.4.0                                                                                                    [0m
    [31mtyping                [0m [36m3.7.4                                                                                                    [0m
    [31murllib3               [0m [36m1.25.3                                                                                                   [0m
    [31mwcwidth               [0m [36m0.1.7                                                                                                    [0m
    [31mwebencodings          [0m [36m0.5.1                                                                                                    [0m
    [31mwheel                 [0m [36m0.33.4                                                                                                   [0m
    [31mwidgetsnbextension    [0m [36m3.5.0                                                                                                    [0m
    [31mwrapt                 [0m [36m1.11.2                                                                                                   [0m
    [31myapf                  [0m [36m0.27.0                                                                                                   [0m
    [31mzipp                  [0m [36m0.5.1                                                                                                    [0m

**Comment by galaunay** [comment]
It looks like `compilation-mode` cannot handle the color codes.

You can try `M-x compile RET poetry --ansi -n show`, if you see the same gibberish in the buffer that will pop, there is definitely a problem in compilation-mode, and you should report there.

As a workaround, you can overwrite `poetry-do-call` function with the following one:
```Elisp
(defun poetry-do-call (command &optional args project output blocking)
  "Call poetry COMMAND with the given ARGS.

Not queue-safe version of `poetry-call'.

PROJECT is the poetry project you want the command to be run for
\(default to the current project).
If OUTPUT is non-nil, display the compilation buffer.
If BLOCKING is non-nil, wait until the compilation is over and return the
compilation buffer name."
  (let ((default-directory (or project
                               (poetry-find-project-root)
                               default-directory)))
    (unless (member command '(new init config))
      (poetry-ensure-in-project))
    (let* ((prog (or (executable-find "poetry")
                     (poetry-error "Could not find 'poetry' executable")))
           (args (if (or (string= command "run")
                         (string= command "init"))
                     (cl-concatenate 'list (list (symbol-name command))
                                     args)
                   (cl-concatenate 'list (list "-n" "--no-ansi"
                                               (symbol-name command))
                                   args))))
      (let ((compilation-buffer-name-function
             (lambda (_mode) (poetry-buffer-name)))
            (compilation-ask-about-save nil)
            (compilation-save-buffers-predicate (lambda () nil)))
        (save-window-excursion
          (compile (concat prog " " (string-join args " "))))
        (setq poetry-process
              (get-buffer-process (get-buffer (poetry-buffer-name))))
        ;; Block until completion if asked
        (when blocking
          (while (or (eq (process-status poetry-process) 'run)
                      ;; Poetry buffer should be cleaned from compilation-mode verbose
                     (with-current-buffer (poetry-buffer-name)
                       (goto-char (point-min))
                       (re-search-forward "mode: compilation;" nil t)))
            (sleep-for .1)))
        ;; Display the buffer if asked
        (if output
            (with-current-buffer (poetry-buffer-name)
              (let ((new-name (poetry-buffer-name "output")))
                (when (get-buffer new-name) (kill-buffer new-name))
                (poetry-display-buffer (rename-buffer new-name))
                new-name))
          (poetry-buffer-name))))))
```

**Comment by Yevgnen** [comment]
It does happen with `M-x compile RET poetry --ansi -n show`


    -*- mode: compilation; default-directory: "~/Git/demo/" -*-
    Compilation started at Sat Jul 20 16:04:45

    poetry --ansi -n show

    [[31mRuntimeError[0m]                                                                                
    [31mPoetry could not find a pyproject.toml file in /Users/user/Git/demo or its parents  [0m

    [32mshow [--no-dev] [-t|--tree] [-l|--latest] [-o|--outdated] [-a|--all] [--] [[0m[32m<package>[0m[32m][0m


    Compilation exited abnormally with code 1 at Sat Jul 20 16:04:47

**Comment by galaunay** [comment]
I am afraid this is compilation-mode failing to parse your shell color codes.
As it is part of Emacs, you will need to report to Emacs directly with `M-x report-emacs-bug`.

Is the workaround I provided helps ?

**Comment by lerouxrgd** [comment]
I had the same issue with `Emacs 26.3` on Archlinux. Your workaround worked.
Should it be the default ?

**Comment by galaunay** [comment]
As the workaround works, it does not allow to keep the font colors from poetry.

I found a proper fix and commited it just now (c541427).
Could you update and see if it fixes your problem ?

**Comment by lerouxrgd** [comment]
It works perfectly, thank you !

**Comment by galaunay** [comment]
Great !
 I am closing this issue then.
